
<?php
require $_SERVER["DOCUMENT_ROOT"] . "/healthcare/guide/lib/config.php";
$rootIndex = 3;
?>
<?php callHeadCnt();?>
<script>
$(document).ready(function() {
	mobiQrCode();
	winPopup();
	milestoneBd(1);
});
</script>
</head>
<body>
<div id="document">
	<header>
		<h1><a href="/healthcare/guide/"><strong><?php echo TITLE ?></strong> - SA Guide</a></h1>
		<nav id="globalNavi">
			<?php callMainMenu();?>
		</nav>
	</header>
	<div id="container">
		<h2>작업현황판 - <em>mEMR - Admin</em></h2>
		<p class="info">
			△ : 작업중  ○ : 마크업 완료  
		</p>
		<div class="directory">
			<table border="1" summary="작업 디렉토리구조도입니다.">
				<caption>디렉토리 구조도</caption>
				<colgroup>
					<col width="50px" />
					<col width="%" />
					<col width="%" />
					<col width="%" />
					<col width="%" />
					<col width="%" />
					<col width="%" />
					<col width="%" />
					<col width="%" />
				</colgroup>
				<thead>
					<tr>
						<th>구분</th>
						<th>N1</th>
						<th>N2</th>
						<th>N3</th>
						<th>N4</th>
						<th>N5</th>
						<th>실작업 페이지</th>
						<th>UI</th>
						<th>GUI</th>
						<th>Publish</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td></td>
						<td>Global</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>-</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>수정</td>
						<td></td>
						<td>Sign in</td>
						<td></td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/login</td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/home/login.php">mEMR_login</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td>LogIn InvalidDataAlert</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/home/login_pop.php">mEMR_login_popup</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>삭제</td>
						<td></td>
						<td>LogOut</td>
						<td></td>
						<td></td>
						<td></td>
						<td>0</td>
						<td>/logout</td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td>LogOut SuccessResult</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/goodbye</td>
						<td>X</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>삭제</td>
						<td></td>
						<td>FindID</td>
						<td></td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/accounts/find</td>
						<td>X</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td>FindPW</td>
						<td></td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/accounts/find</td>
						<td>X</td>
						<td><a href="/healthcare/IPC/home/login_forgot.php">IPC_login_forgot password</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td>Global Common</td>
						<td></td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>-</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td>Global Common UnloadConfirm</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td>mEMR_usermanagement_user_adduser_popup_01</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td>UserManagement</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>-</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td>UserManagement User</td>
						<td></td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>수정</td>
						<td></td>
						<td></td>
						<td>UserManagement User List</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/members</td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/usermanagement/group_userlist.php">mEMR_usermanagement_user</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td>UserManagement User Detail</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/members/{id}</td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/usermanagement/user_detailview.php/">mEMR_usermanagement_user_detailview</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td>UserManagement User Add</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/members/add</td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/usermanagement/user_adduser.php/">mEMR_usermanagement_user_adduser</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td>UserManagement User Edit</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/members/{id}/edit</td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/usermanagement/user_edituser.php/">mEMR_usermanagement_user_edituser</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td>UserManagement User Common</td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>-</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>삭제</td>
						<td></td>
						<td></td>
						<td></td>
						<td>UserManagement User Common InviteConfirm</td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>X</td>
						<td> </td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>삭제</td>
						<td></td>
						<td></td>
						<td></td>
						<td>UserManagement User Common InviteResult</td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td>UserManagement User Common DeleteConfirm</td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/usermanagement/user_edituser_confirm.php">mEMR_usermanagement_user_confirm_01</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>미정</td>
						<td></td>
						<td></td>
						<td></td>
						<td>UserManagement User Common ImportResult</td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>X</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td>UserManagement User Common InvalidDataAlert</td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td>mEMR_usermanagement_user_adduser_popup_05</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td>UserManagement User Common CancelConfirm</td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/usermanagement/user_adduser_pop02.php">mEMR_usermanagement_user_adduser_popup_02</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td></td>
						<td>UserManagement User Common OrgTooltip</td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td>UserManagement User Invitemailsending</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/members/invite</td>
						<td>O</td>
						<td>mEMR_usermanagement_user_invite</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td>UserManagement Org</td>
						<td></td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>-</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>수정</td>
						<td></td>
						<td></td>
						<td>UserManagement Org List</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/members/organizations</td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/usermanagement/org_mz.php/">org_mz</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>삭제</td>
						<td></td>
						<td></td>
						<td>UserManagement Org Detail</td>
						<td></td>
						<td></td>
						<td>0</td>
						<td>/members/organizations/{id}</td>
						<td>X</td>
						<td><a target="_blank" href="/healthcare/mEMR/usermanagement/org_detailview.php">mEMR_usermanagement_org_detailview</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td>UserManagement Org Add</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/members/organizations/add</td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/usermanagement/org_add.php">mEMR_usermanagement_org_add</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>수정</td>
						<td></td>
						<td></td>
						<td>UserManagement Org Edit</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/members/organizations/{id}/edit</td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/usermanagement/org_edit_mz.php">org_edit_mz</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td>UserManagement Org Common</td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>-</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td>UserManagement Org Common DeleteConfirm</td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/usermanagement/org_delete.php">mEMR_usermanagement_org_delete</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>미정</td>
						<td></td>
						<td></td>
						<td></td>
						<td>UserManagement Org Common ImportResult</td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>X</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td>UserManagement Group</td>
						<td></td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>-</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>수정</td>
						<td></td>
						<td></td>
						<td>UserManagement Group List</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/members/roles</td>
						<td>O</td>
						<td>mEMR_usermanagement_group_userlist</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>삭제</td>
						<td></td>
						<td></td>
						<td>UserManagement Group Detail</td>
						<td></td>
						<td></td>
						<td>0</td>
						<td>/members/roles/{id}</td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/usermanagement/group_mz.php">group_mz</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td>UserManagement Group Add</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/members/roles/add</td>
						<td>O</td>
						<td>mEMR_usermanagement_group_add group</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>수정</td>
						<td></td>
						<td></td>
						<td>UserManagement Group Edit</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/members/roles/{id}/edit</td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/usermanagement/group_edit_gruop_mz.php">group_edit_gruop_mz</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td>UserManagement Group Common</td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>-</td>
						<td><a target="_blank" href="/healthcare/mEMR/usermanagement/group_edit_gruop_moveto_mz.php">group_edit_gruop_moveto_mz</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>미정</td>
						<td></td>
						<td></td>
						<td></td>
						<td>UserManagement Group Common DeleteConfirm</td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>X</td>
						<td>mEMR_usermanagement_org_delete</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td>UserManagement Common</td>
						<td></td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>-</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td>UserManagement Common SelectMember</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/usermanagement/user_invite_mail_pop_add_user.php" taget="_blank">mEMR_usermanagement_invite_add</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td>UserManagement Common Group</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td>mEMR_usermanagement_org_move</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td>UserManagement Common Org</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td>mEMR_usermanagement_org_move</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td>DeviceManagement</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>-</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td>DeviceManagement List</td>
						<td></td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/devices</td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/devicemanagement/device_management_list.php">mEMR_device_management_list</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td>DeviceManagement Detail</td>
						<td></td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/devices/{id}</td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/devicemanagement/device_management_detail_view.php">mEMR_device_management_detailview</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td>DeviceManagement Edit</td>
						<td></td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/devices/{id}/edit</td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/devicemanagement/device_management_edit.php">mEMR_device_management_edit</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td>DeviceManagement Common</td>
						<td></td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>미정</td>
						<td></td>
						<td></td>
						<td>DeviceManagement Common ApproveConfirm</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>X</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>삭제</td>
						<td></td>
						<td></td>
						<td>DeviceManagement Common DenyConfirm</td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>X</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>미정</td>
						<td></td>
						<td></td>
						<td>DeviceManagement Common ImportResult</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>X</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td>DeviceManagement Member</td>
						<td></td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>-</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td>DeviceManagement Member List</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/usermanagement/user_invite_mail_pop_add_user.php" taget="_blank">mEMR_usermanagement_invite_add</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>삭제</td>
						<td></td>
						<td></td>
						<td>DeviceManagement Member Detail</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>X</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>삭제</td>
						<td></td>
						<td></td>
						<td>DeviceManagement Member Edit</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>X</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td>DeviceManagement Shared Device List</td>
						<td></td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>X</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td>DeviceManagement Shared Device Detail</td>
						<td></td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>X</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td>DeviceManagement Shared Device Common</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td>DeviceManagement Common ApproveConfirm</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>X</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td>History</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>-</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>수정</td>
						<td></td>
						<td>History Sign in</td>
						<td></td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>-</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>수정</td>
						<td></td>
						<td></td>
						<td>History Signin List</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/histories/</td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/history/history_login.php">mEMR_history_login</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>삭제</td>
						<td></td>
						<td></td>
						<td>History Signin Detail</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/histories/</td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/history/history_detail_view.php">mEMR_history_login_detail view</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td>History UserFunction</td>
						<td></td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>-</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td>History UserFunction List</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/histories/</td>
						<td>X</td>
						<td><a target="_blank" href="/healthcare/mEMR/history/history_user.php">mEMR_history_used function</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>삭제</td>
						<td></td>
						<td></td>
						<td>History UserFunction Detail</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/histories/</td>
						<td>X</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td>History EmergencyAccess</td>
						<td></td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>-</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td>History EmergencyAccess List</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/histories/</td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/history/history_emergency.php">mEMR_history_emergency access</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td>History EmergencyAccess Detail</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/histories/</td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/history/history_emergency_detail_view.php">mEMR_history_emergency access_detailview</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td>History Common</td>
						<td></td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>-</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td>History Common Calendar</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td>mEMR_history_login_calendar</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td>History Common  InvalidDataAlert</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td>mEMR_usermanagement_user_adduser_popup_05</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td>AnatomyImageLibrary</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>-</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td>AnatomyImageLibrary Contents</td>
						<td></td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>-</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td>AnatomyImageLibrary Contents List</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/anatomies</td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/anantomy/contents_list.php">mEMR_anatomy_contents_list</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td>AnatomyImageLibrary Contents Detail</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/anatomies/{id}</td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/anantomy/contents_category_detail_view.php">mEMR_anatomy_category_detailview</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td>AnatomyImageLibrary Contents Add</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/anatomies/add</td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/anantomy/contents_addimage.php">mEMR_anatomy_contents_addimage</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td>AnatomyImageLibrary Contents Edit</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/anatomies/{id}/edit</td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/anantomy/contents_editimage.php">mEMR_anatomy_contents_editimage</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td>AnatomyImageLibrary Contents Common</td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>-</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td>AnatomyImageLibrary Contents Common DeleteConfirm</td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td>mEMR_usermanagement_org_delete</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>삭제</td>
						<td></td>
						<td></td>
						<td></td>
						<td>AnatomyImageLibrary Contents Common ActiveConfirm</td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>X</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>삭제</td>
						<td></td>
						<td></td>
						<td></td>
						<td>AnatomyImageLibrary Contents Common InactiveConfirm</td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>X</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>수정</td>
						<td></td>
						<td>AnatomyImageLibrary Category</td>
						<td></td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>-</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>수정</td>
						<td></td>
						<td></td>
						<td>AnatomyImageLibrary Category List</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/anatomies/categories</td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/anantomy/contents_category_list.php">mEMR_anatomy_category</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>수정</td>
						<td></td>
						<td></td>
						<td>AnatomyImageLibrary Category Add</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/anatomies/categories/add</td>
						<td>O</td>
						<td>mEMR_usermanagement_org_add</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>수정</td>
						<td></td>
						<td></td>
						<td>AnatomyImageLibrary Category Edit</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/anatomies/categories/{id}/edit</td>
						<td>X</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td>AnatomyImageLibrary Category Common</td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>-</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td>AnatomyImageLibrary Category Common DeleteConfirm</td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>미정</td>
						<td></td>
						<td></td>
						<td></td>
						<td>AnatomyImageLibrary Category Common ActiveConfirm</td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>X</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>미정</td>
						<td></td>
						<td></td>
						<td></td>
						<td>AnatomyImageLibrary Category Common InactiveConfirm</td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>X</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td>AnatomyImageLibrary Common</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td>AnatomyImageLibrary Common Category</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td>Admin Management</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>수정</td>
						<td></td>
						<td>AdminManagement MyInfo</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td>AdminManagement AdminAccount</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td>AdminManagement AdminAccount List</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td>AdminManagement AdminAccount Detail</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td>AdminManagement AdminAccount Add</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td>AdminManagement AdminAccount Edit</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td>AdminManagement AdminAccount Common</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td>AdminManagement SigninHistory</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td>AdminManagement SigninHistory List</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>수정</td>
						<td></td>
						<td>AdminManagement UserGroupHistory</td>
						<td></td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>-</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>수정</td>
						<td></td>
						<td></td>
						<td>History Group List</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/histories/</td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/history/history_group.php">mEMR_history_user group</a></td>
						<td>-</td>
						<td></td>
					</tr>
					<tr>
						<td>수정</td>
						<td></td>
						<td></td>
						<td>History Group Detail</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/histories/</td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/history/history_group_detail_view.php">mEMR_history_user group_detail view</a></td>
						<td>-</td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td>AdminManagement Common</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td>AdminManagement Common Calendar</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td>AdminManagement Common InvalidDataAlert</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td>Client App Management</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>X</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td>ClientAppManagement mEMR App</td>
						<td></td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>X</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td>ClientAppManagement mEMRApp List</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td>ClientAppManagement mEMRApp Detail</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td>ClientAppManagement mEMRApp Add</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td>ClientAppManagement mEMRApp Edit</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td>ClientAppManagement mEMRApp Common</td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>X</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td></td>
						<td>ClientAppManagement mEMRApp Common DeleteConfirm</td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td></td>
						<td>ClientAppManagement mEMRApp Common InvalidDataAlert</td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td></td>
						<td>ClientAppManagement mEMRApp Common ActiveConfirm</td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td></td>
						<td>ClientAppManagement mEMRApp Common InactiveConfirm</td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td></td>
						<td>ClientAppManagement mEMRApp Common CancelConfirm</td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td></td>
						<td>ClientAppManagement mEMRApp Common ExtraAppSelect</td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td>ClientAppManagement Extra App</td>
						<td></td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>X</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td>ClientAppManagement ExtraApp List</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td>ClientAppManagement ExtraApp Detail</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td>ClientAppManagement ExtraApp Add</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td>ClientAppManagement ExtraApp Edit</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td>ClientAppManagement ExtraApp Common</td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>X</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td></td>
						<td>ClientAppManagement ExtraApp Common DeleteConfirm</td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td></td>
						<td>ClientAppManagement ExtraApp Common InvalidDataAlert</td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td></td>
						<td>ClientAppManagement ExtraApp Common CancelConfirm</td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td>ClientAppManagement mEMR Tester</td>
						<td></td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>X</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td>ClientAppManagement mEMRTester List</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td>ClientAppManagement mEMRTester Common</td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>X</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td></td>
						<td>ClientAppManagement mEMRTester Common DeleteConfirm</td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td></td>
						<td>ClientAppManagement mEMRTester Common SelectMember</td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td>Settings</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>-</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>수정</td>
						<td></td>
						<td>Settings ClientManagement</td>
						<td></td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>-</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>수정</td>
						<td></td>
						<td></td>
						<td>Settings ClientManagement Detail</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td>/settings</td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/setting/setting.php">mEMR_settings</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>삭제</td>
						<td></td>
						<td>Settings Admin Account</td>
						<td></td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>-</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>삭제</td>
						<td></td>
						<td></td>
						<td>Settings AdminAccount Detail</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td>Settings Server Storage</td>
						<td></td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>-</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td>Settings ServerStorage Detail</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td><a target="_blank" href="/healthcare/mEMR/setting/storage.php">mEMR_settings_admin account</a></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td>Settings Position Management</td>
						<td></td>
						<td></td>
						<td></td>
						<td>0</td>
						<td></td>
						<td>-</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td></td>
						<td>Settings PositionManagement Detail</td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td>Settings Hospital Management</td>
						<td></td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td>9.1.Settings_Hospital Management</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td>신규</td>
						<td></td>
						<td>Settings My Info</td>
						<td></td>
						<td></td>
						<td></td>
						<td>1</td>
						<td></td>
						<td>O</td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td>93</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
<?php callFootCnt();?>